config/routes.rb
Rails.application.routes.draw do
  root to: 'member_tests#index'

  get '/user_matrix', to: 'application#user_matrix'
  get '/public_test', to: 'application#public_test'

  devise_for :companies
  namespace :api do
    get :ping, controller: 'application'
    resources :matrix, only: :index
  end

  resources :settings, only: :index do
    get :regenerate, on: :collection
  end
  
  resources :test_groups
  resources :tests
  resources :members do
    member do
      get :close_test
    end    
  end
  resources :member_groups
  resources :member_tests do
    member do
      get :history
      get :pass_form
      post :pass
      get :regenerate
    end
  end
  resources :questions
end

app/models/member_test.rb
# == Schema Information
#
# Table name: member_tests
#
#  id         :bigint           not null, primary key
#  status     :string           default("draft"), not null
#  member_id  :bigint
#  test_id    :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class MemberTest < ApplicationRecord
  belongs_to :member
  belongs_to :test

  has_many :member_test_questions, dependent: :destroy
  has_many :attempts, dependent: :destroy

  enum status: { draft: "draft", started: "started", passed: "passed", failed: "failed" }

  validates :test_id, uniqueness: { scope: :member_id }
  
  after_create :populate_member_test_questions
  before_update :check_results

  accepts_nested_attributes_for :member_test_questions, allow_destroy: true
  
  def get_temp_token
    payload = { id: self.id }
    payload[:exp] = 20.minutes.from_now.to_i
    JWT.encode(payload, Rails.configuration.JWT_SECRET)
  end

  def regerenate!
    member_test_questions.destroy_all
    update_column(:status, :draft)
    populate_member_test_questions
  end

  def is_question_right question
    return question.answer_id? ? question.answer_id == question.question.right_answer&.id : false
  end

  def count_rights
    right_count = 0
    member_test_questions.each do |question|
      right_count += 1 if is_question_right question
    end 
    return right_count
  end

  private

  def check_results
    if self.status_was === 'started'
      right_count = count_rights
      self.status = right_count >= test.pass_count ? :passed : :failed
    end
  end

  def populate_member_test_questions
    test.questions.order("RANDOM()").limit(test.questions_count).each do |question|
      mtq = member_test_questions.create!(question_id: question.id)
      question.answers.order('Random()').pluck(:id).each_with_index do |x, i| 
        mtq.member_test_question_answers.create!(answer_id: x, label: ('A'..'Z').to_a[i])
      end
    end
  end
end

app/controllers/member_tests_controller.rb
class MemberTestsController < ApplicationController
  before_action :set_member_test, only: %i[show edit update destroy pass_form pass regenerate history]
  before_action :validate_regeneration, only: %i[regenerate]

  def index
    @status_filter = MemberTest.statuses.keys.include?(params[:status]) ? params[:status] : 'draft'
    @member_tests = current_company.member_tests.where(status: @status_filter).eager_load(:member, test: :test_group).order('members.name, test_groups.name, tests.module')
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Invoice No. #{@member_test.id}",
        page_size: 'A4',
        template: "member_tests/pdf.slim",
        encoding: "utf8",
        layout: "pdf.html",
        orientation: "Portrait",
        margin: { left: 0, right: 0 },
        header: { html: { template: "layouts/pdf_header.slim" }, spacing: 20 }, 
        footer: { html: { template: "layouts/pdf_footer.slim" } }, 
        lowquality: true,
        zoom: 1,
        dpi: 75
      end
    end
  end

  def new
    @member_test = MemberTest.new(member_id: params[:member_id])
  end

  def create
    @member_test = current_company.member_tests.new(member_test_params)
    if @member_test.save
      redirect_to @member_test, notice: 'Member test was successfully created.'
    else
      render :new
    end
  end

  def regenerate
    @member_test.regerenate!
    redirect_to @member_test, notice: 'Member test was successfully regenerated.'
  end

  def destroy
    @member_test.destroy
    redirect_to member_tests_url, notice: 'Member test was successfully destroyed.'
  end

  def pass_form
    @member_test.update(status: 'started') if @member_test.draft?
  end

  def pass
    if @member_test.update(pass_params)
      @member_test.attempts.create(result: @member_test.count_rights, status: @member_test.status)
      redirect_to @member_test, notice: 'Member test was completed.'
    else
      render :pass_form
    end
  end

  def history; end

  private
    def set_member_test
      @member_test = current_company.member_tests.find(params[:id])
    end

    def member_test_params
      params.require(:member_test).permit(:passed, :member_id, :test_id)
    end

    def pass_params
      params.require(:member_test).permit(member_test_questions_attributes: [:id, :answer_id])
    end

    def validate_regeneration
      set_member_test
      redirect_back fallback_location: root_path, notice: 'Cannot regenerate started tests' if @member_test.started?
    end
end

app/views/member_tests/_form.slim
= semantic_form_for member_test do |f| 
  = f.inputs do
    = f.input :member, as: :select, collection: current_company.members.order(:name).pluck(:name, :id)
    = f.input :test, as: :select, collection: current_company.tests.joins(:test_group).order('test_groups.name, tests.module').map { |test| ["#{test.test_group.name} - #{test.name}", test.id] }
  = f.actions
    = f.action :cancel, as: :link, button_html: { class: 'btn btn--secondary' }
    = f.action :submit, as: :button, button_html: { class: 'btn btn--primary' }

app/views/member_tests/history.slim
= render "layouts/table" do
  h1 History

  .table-outer
    table.table.table-striped.table--test-groups
      thead
        tr
          th Result
          th Status
          th Date
      tbody
        - @member_test.attempts.each do |attempt|
          tr
            td = attempt.result
            td = attempt.status.capitalize
            td = attempt.created_at.strftime('%F')
  <br>

app/views/member_tests/index.slim
= render "layouts/table" do

  .table-title-container
    .table-title-section
      h1 Member tests
      = link_to 'New member test', new_member_test_path, class: 'btn btn--primary'
    .table-filters
      - MemberTest.statuses.keys.each_with_index do |status, index|
        = link_to status.capitalize , url_for(status: status), class: ['btn btn--borderless', @status_filter == status ? 'btn--black btn--unclickable' : 'btn--white'].join(' ')
        - if index != MemberTest.statuses.keys.size - 1
          .vertical-divider
    
  
  .table-outer
    table.table.table-striped.table--member-tests
      thead
        tr
          th Member
          th Test
          th Status
          th Last attempted at
          th.table-column-actions4 Actions 

      tbody
        - @member_tests.each do |member_test|
          tr
            td = link_to member_test.member.name, member_test.member, class: 'link'
            td = link_to "#{member_test.test.test_group.name} (#{member_test.test.name})", member_test.test, class: 'link'
            td = member_test.status.capitalize
            td = member_test.attempts.last&.created_at&.strftime('%F') || 'Not attempted yet'
            td
              = link_to 'Show', member_test_path(member_test), class: 'btn btn--black btn--inline'
              = link_to 'Print', member_test_path(member_test, format: :pdf), target: '_blank', class: 'btn btn--black btn--inline'
              = link_to 'Pass', pass_form_member_test_path(member_test), class: 'btn btn--black btn--inline'
              - unless member_test.started?
                = link_to 'Regenerate', regenerate_member_test_path(member_test), class: 'btn btn--white btn--inline'
              = link_to 'Destroy', member_test, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn--white btn--inline'
  <br>

app/views/member_tests/new.slim
= render 'layouts/form' do
  .new-form
    .new-form--content
      .new-form--content--title
        h1 New Member Test
      .new-form--content--form
        = render 'form', member_test: @member_test
        .new-form--content--form--image.member-test-img

app/views/member_tests/pass_form.slim
= render 'layouts/form' do
  .pass-form
    .pass-form--content
      .pass-form--content--title
        h2 Pass test
        h1 = @member_test.test.name
    .pass-form--content--form
      = semantic_form_for @member_test, url: pass_member_test_path, method: :post do |f|
        = f.inputs do
          - index = 0
          - f.semantic_fields_for :member_test_questions, @member_test.member_test_questions.order(:id) do |a|
            - index += 1
            .pass-question
              .pass-question--container
                .pass-question--label
                  = "Q#{index}:"
                .pass-question--text
                  = a.object.question.text
                = a.input :answer_id, as: :radio , collection: a.object.member_test_question_answers.order(:label).pluck(:label, :answer_id)
              .bottom-pad
        p.caption That's all, check yourself once again to make sure of your results
        = f.actions
          = f.action :cancel, as: :link, button_html: { class: 'btn btn--secondary' }
          = f.action :submit, as: :button, label: 'Submit', button_html: { class: 'btn btn--primary' }

app/views/member_tests/pdf.slim
.pdf
  .pdf--header
    .test-name 
      = "#{@member_test.test.test_group.name} (#{@member_test.test.name})"
    .member-name
      ' for member:
      = @member_test.member.name

  .pdf--body
    .container
      - @member_test.member_test_questions.order(:id).each_with_index do |member_test_question, index|
        .question
          .question--text
            .question--label
              = "#{index + 1}."
            .question--text
              = "#{member_test_question.question.text.strip}"
          .answers
            - member_test_question.member_test_question_answers.each do |member_test_question_answer|
              .answer
                .answer--label
                  = "#{member_test_question_answer.label}:"
                .answer--text = member_test_question_answer.answer.text.strip
      .page-break
      .table-page
        h3 leave your answers here
        .answer--section
          - @member_test.member_test_questions.each_with_index do |_, i|
            .answer--container
              .answer--field
                = i + 1
              .answer--field

app/views/member_tests/show.slim
= render "layouts/show_page" do
  = render partial: 'layouts/questions', locals: { include_actions: true }