config/routes.rb
Rails.application.routes.draw do
  root to: 'member_tests#index'

  get '/user_matrix', to: 'application#user_matrix'
  get '/public_test', to: 'application#public_test'

  devise_for :companies
  namespace :api do
    get :ping, controller: 'application'
    resources :matrix, only: :index
  end

  resources :settings, only: :index do
    get :regenerate, on: :collection
  end
  
  resources :test_groups
  resources :tests
  resources :members do
    member do
      get :close_test
    end    
  end
  resources :member_groups
  resources :member_tests do
    member do
      get :history
      get :pass_form
      post :pass
      get :regenerate
    end
  end
  resources :questions
end

app/models/test_group.rb
# == Schema Information
#
# Table name: test_groups
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  company_id :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  position   :integer          default(0)
#
class TestGroup < ApplicationRecord
  belongs_to :company

  has_many :tests
  has_many :member_group_test_groups
  has_many :member_groups, through: :member_group_test_groups
  
  validates :name, uniqueness: { scope: :company_id, message: 'Duplicate test groups not allowed' }
end

app/controllers/test_groups_controller.rb
class TestGroupsController < ApplicationController
  before_action :set_test_group, only: %i[show edit update destroy]

  def index
    @test_groups = current_company.test_groups.order(:position)
  end
  
  def show; end

  def new
    @test_group = TestGroup.new
  end

  def edit; end 

  def create
    @test_group = current_company.test_groups.new(test_group_params)
    if @test_group.save
      redirect_to @test_group, notice: 'Test group was successfully created.'
    else
      render :new
    end
  end

  def update
    if @test_group.update(test_group_params)
      redirect_to @test_group, notice: 'Test group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @test_group.destroy
    redirect_to test_groups_path, notice: 'Test group was successfully destroyed.'
  end

  private
  
    def set_test_group
      @test_group = current_company.test_groups.find(params[:id])
    end

    def test_group_params
      params.require(:test_group).permit(:name, :position, member_group_ids: [])
    end
end

app/views/test_groups/_form.slim
= semantic_form_for test_group do |f| 
  = f.inputs do
    = f.input :name
    = f.input :position
    = f.input :member_groups, as: :select, collection: current_company.member_groups.pluck(:name, :id), input_html: { class: 'mutli-select' }, wrapper_html: { class: 'multi-select--container' }
  = f.actions
    = f.action :cancel, as: :link, button_html: { class: 'btn btn--secondary' }
    = f.action :submit, as: :button, button_html: { class: 'btn btn--primary' }

app/views/test_groups/edit.slim
= render 'layouts/form' do
  .new-form
    .new-form--content
      .new-form--content--title
        h1 Editing test group
      .new-form--content--form
        = render 'form', test_group: @test_group

app/views/test_groups/index.slim
= render "layouts/table" do
  h1 Test Groups
  = link_to 'New Test Group', new_test_group_path, class: 'btn btn--primary right'

  .table-outer
    table.table.table-striped.table--test-groups
      thead
        tr
          th Name
          th Position
          th Created at
          th Actions

      tbody
        - @test_groups.each do |test_group|
          tr
            td = link_to test_group.name, test_group, class: 'link'
            td = test_group.position
            td = test_group.created_at.strftime('%F')
            td
              = link_to 'Edit', edit_test_group_path(test_group), class: 'btn btn--white btn--inline'
              = link_to 'Destroy', test_group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn--black btn--inline'

  <br>

app/views/test_groups/new.slim
= render 'layouts/form' do
  .new-form
    .new-form--content
      .new-form--content--title
        h1 New test group
      .new-form--content--form
        = render 'form', test_group: @test_group
        .new-form--content--form--image.test-img

app/views/test_groups/show.slim
= render "layouts/table" do
  .title
    h1
      = @test_group.name
    h2 Tests
  .show-page-actions
    = link_to 'New test', new_test_path(test_group_id: @test_group.id), class: 'btn btn--primary'
    = link_to 'Edit', edit_test_group_path(@test_group), class: 'btn btn--black'
  .table-outer
    table.table.table-striped.table--test-group
      thead
        tr
          th Test name
          th Questions count
          th Pass count
          th Created at
          th Actions

      tbody
        - @test_group.tests.each do |test|
          tr
            td = link_to test.name, test, class: "link"
            td = test.questions_count
            td = test.pass_count
            td = test.created_at.strftime('%F')
            td
              = link_to 'Edit', edit_test_path(test), class: 'btn btn--white btn--inline'
              = link_to 'Destroy', test, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn--black btn--inline'