config/routes.rb
Rails.application.routes.draw do
  root to: 'member_tests#index'

  get '/user_matrix', to: 'application#user_matrix'
  get '/public_test', to: 'application#public_test'

  devise_for :companies
  namespace :api do
    get :ping, controller: 'application'
    resources :matrix, only: :index
  end

  resources :settings, only: :index do
    get :regenerate, on: :collection
  end
  
  resources :test_groups
  resources :tests
  resources :members do
    member do
      get :close_test
    end    
  end
  resources :member_groups
  resources :member_tests do
    member do
      get :history
      get :pass_form
      post :pass
      get :regenerate
    end
  end
  resources :questions
end

app/views/layouts/_footer.slim
footer.footer
  .footer--border--container
    .footer--border--container--line
  .footer--content
    .footer--content--title Powered by Leviossa IT with love and magic
    .footer--content--social-icons
      = link_to("https://leviossa.net/", class:"footer-link", target: '_blank')
        = image_tag('leviossa_logo_white.png', class: "img-icon upwork")
      = link_to("https://www.upwork.com/o/companies/~013566a58d9bf10f22/", class:"footer-link", target: '_blank')
        = image_tag('upwork_icon.png', class: "img-icon upwork")
      = link_to("https://www.facebook.com/LeviossaIT/", class:"footer-link", target: '_blank')
        = image_tag('fb_icon.png', class: "img-icon facebook")
      = link_to("https://www.instagram.com/leviossa_team", class:"footer-link", target: '_blank')
        = image_tag('insta_icon.png', class: "img-icon instagram")
      = link_to("https://vk.com/leviossa_team", class:"footer-link", target: '_blank')
        = image_tag('vk_icon.png', class: "img-icon vk")
      = link_to("https://www.linkedin.com/company/leviossa/", class:"footer-link", target: '_blank')
        = image_tag('linkedin_icon.png', class: "img-icon linked-in")
      = link_to("https://clutch.co/profile/leviossa-it", class:"footer-link", target: '_blank')
        = image_tag('clutchio_icon.png', class: "img-icon clutch-io")
      = link_to("https://angel.co/company/leviossa-it", class:"footer-link", target: '_blank')
        = image_tag('angellist_icon.png', class: "img-icon angellist")

app/views/layouts/_form.slim
.form
  = yield

app/views/layouts/_matrix.slim
.table-outer
  - columns_count = tests_container.tests.maximum(:module).to_i
  table.table.table-striped.table--matrix
    thead
      col width="18%"
      - columns_count.times do |col|
        col width="#{(82/columns_count).ceil}%"
      tr
        th Name
        - columns_count.times do |col|
          th = "Module #{col + 1}"

    tbody
      - is_auth = company_signed_in? && !(defined?(is_public) && is_public)
      - tests_container.test_groups.order(:position).each do |test_group|
        tr
          td = link_to_if is_auth, test_group.name, test_group, class: 'link'
          - columns_count.times do |index|
            - test = test_group.tests.find_by(module: index + 1)
            - member_test = test.member_tests.find_by(member: member) if test.present? && defined?(member)
            - is_active = member_test.present? && !member_test.passed?
            - is_passed = member_test&.passed?
            td class=(['test', is_active ? 'test--started' : nil, is_passed ? 'test--passed' : nil].compact.join(' '))  
              - if test.present?
                .test-title = link_to_if is_auth, test.name, test, class: ['link', is_passed ? 'link--white' : nil].compact.join(' ')
                .test-subtitle = "Value: #{test.value}"
                - if is_auth
                  .test-subtitle = "Questions: #{test.questions.count}/#{test.questions_count}/#{test.pass_count}"
                div = test.description
                - if is_passed
                  = image_tag('test_check_mark.svg', class: 'pass-triangle')
                - elsif defined?(member) && is_auth
                    .close-triangle
                    = link_to_if is_auth, '', close_test_member_path(@member, test_id: test.id), class: 'close-link'
                    = image_tag('twitter.svg', class: 'close-icon')

app/views/layouts/_navbar.slim
nav.navbar
    .navbar--content
      .navbar--trigger 
        button id="ham" class="hamburger hamburger--spring" type="button"
          span class="hamburger-box"
            span class="hamburger-inner"
        javascript:
          document.querySelector('.hamburger').addEventListener('click', (event) => {
            document.querySelectorAll('#ham').forEach(item => item.classList.toggle('is-active'));
          })
      - if company_signed_in?
        .navbar--headers
          = link_to(current_company.name, root_path, class: "navbar--brand navbar--link")
     
      #ham.hamburger.dummy
      .collapse.navbar--collapse#bs--example--navbar--collapse--1
        - if company_signed_in?
          ul.nav.navbar--nav.navbar--items
            li.navbar--item
              = link_to('Member tests', member_tests_path, class: "navbar--link #{is_nav_active('member_tests')}")
            li.navbar--item
              = link_to('Members', members_path, class: "navbar--link #{is_nav_active('members')}")
            li.navbar--item
              = link_to('Member groups', member_groups_path, class: "navbar--link #{is_nav_active('member_groups')}")
            li.navbar--item
              = link_to('Test groups', test_groups_path, class: "navbar--link #{is_nav_active('test_groups')}") 
            li.navbar--item
              = link_to('Tests', tests_path, class: "navbar--link #{is_nav_active('tests')}")
            
              
        ul.nav.navbar--nav.navbar--right
          - if company_signed_in?
            li.navbar--item = link_to('API', settings_path, class: "navbar--link")
            li.navbar--item = link_to('Logout', destroy_company_session_path, method: :delete, class: "navbar--link")
          - else
            - if controller_name != 'sessions'
              li = link_to "Log in", new_session_path(resource_name),class: "navbar--link"
            - if devise_mapping.registerable? && controller_name != 'registrations'
              li = link_to "Sign up", new_registration_path(resource_name), class: "navbar--link"
    .navbar--border--container
      .navbar--border--container--line  

app/views/layouts/_questions.slim
 .show 
    .show--content
      .show--content--title class="#{@member_test.failed? ? 'failed_pass' : 'success_pass'}"
        h1          
          - if @member_test.passed?
            = 'Winner winner chicken dinner'
          - elsif @member_test.failed?
            = 'Better luck next time'
          - else
            = 'Good luck'
        - if @member_test.passed? || @member_test.failed?
          p Your result is #{@member_test.count_rights}/#{@member_test.test.questions_count}
      - if include_actions
        .action--section
          .action--line
            = link_to "To #{@member_test.member.name}", member_path(@member_test.member), class: 'btn btn--secondary'
            = link_to "History", history_member_test_path(@member_test), class: 'btn btn--secondary'
            = link_to "To #{@member_test.test.test_group.name} (#{@member_test.test.name})", test_path(@member_test), class: 'btn btn--secondary'   
          .action--line
            = link_to 'Pass', pass_form_member_test_path(@member_test), class: 'btn btn--secondary'
            - unless @member_test.started?
              = link_to 'Regenerate', regenerate_member_test_path(@member_test), class: 'btn btn--secondary'
            - else
              .btn.btn--secondary.public-page-url-btn data-link="#{public_test_url(token: @member_test.get_temp_token)}" Public page
            = link_to 'Print', member_test_path(@member_test, format: :pdf), class: 'btn btn--primary', target: '_blank'
      .questions
        .questions--header
          h1 In details
        .questions--content
          - @member_test.member_test_questions.order(:id).each_with_index do |member_test_question, index|
            .question-container
              .question--label
                strong = "Q#{index+1}"
                - if @member_test.passed? || @member_test.failed?
                  = image_tag (@member_test.is_question_right(member_test_question)? 'check.svg' : 'cross.svg') 
              .padding
                .question
                  = member_test_question.question.text
                .answer-container
                  - member_test_question.member_test_question_answers.each do |member_test_question_answer|
                    .answer class=(member_test_question.answer_class_name(member_test_question_answer.answer))
                      .answer--label
                        = "#{member_test_question_answer.label}:"
                        = image_tag (member_test_question_answer.answer.is_right? ? 'check.svg' : 'cross.svg')
                      .text
                        = member_test_question_answer.answer.text

app/views/layouts/_show_page.slim
.show-page
  p#notice = notice
  = yield

app/views/layouts/_table.slim
.table-container
  p#notice = notice

  = yield

app/views/layouts/application.slim
doctype html
html
  head
    title LeviTests
    = csrf_meta_tags
    = csp_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = favicon_link_tag asset_path('leviossa_logo_black.png')
    = stylesheet_link_tag    "https://fonts.googleapis.com/css?family=Inter:400,500,600,700,800&display=swap"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .wrapper
      = render 'layouts/navbar' if action_name != 'user_matrix' && action_name != 'public_test'
      = yield
      - if action_name != 'user_matrix' && action_name != 'public_test'
        .push
      = render 'layouts/footer' 

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Levi Tests</title>
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/layouts/pdf_footer.slim
<!DOCTYPE html>
html lang="en"
  head
    meta charset="UTF-8"/
    meta name="viewport" content="width=device-width, initial-scale=1.0"/
    = wicked_pdf_stylesheet_link_tag "pdf"
    title Document
  body
    footer
      .acknowledgement Powered by Leviossa IT
      .page-number
        = wicked_pdf_image_tag "page_number.svg"
        .number 1
        javascript:
          var test = document.querySelector('.number');
          var page = window.location.search.match(/page=(\d+)&/)[1];
          test.innerHTML = page;

app/views/layouts/pdf_header.slim
<!DOCTYPE html>
html lang="en"
  head
    meta charset="UTF-8"/
    meta name="viewport" content="width=device-width, initial-scale=1.0"/
    = wicked_pdf_stylesheet_link_tag "pdf"
    title Document
  body
    header
      .company-name
        = current_company.name
      .boxes
        <svg width="1240" height="150" viewBox="0 0 2480 301" fill="none" xmlns="http://www.w3.org/2000/svg">
          <rect x="621.5" y="-22.5" width="2059" height="321" stroke="#2A2D33" stroke-opacity="0.3" stroke-width="5" stroke-dasharray="7 50.5"/>
          <rect x="-54.5" y="-56.5" width="787" height="250" stroke="#2A2D33" stroke-opacity="0.3" stroke-width="5" stroke-dasharray="7 50.3"/>
        </svg>