config/routes.rb
Rails.application.routes.draw do
  root to: 'member_tests#index'

  get '/user_matrix', to: 'application#user_matrix'
  get '/public_test', to: 'application#public_test'

  devise_for :companies
  namespace :api do
    get :ping, controller: 'application'
    resources :matrix, only: :index
  end

  resources :settings, only: :index do
    get :regenerate, on: :collection
  end
  
  resources :test_groups
  resources :tests
  resources :members do
    member do
      get :close_test
    end    
  end
  resources :member_groups
  resources :member_tests do
    member do
      get :history
      get :pass_form
      post :pass
      get :regenerate
    end
  end
  resources :questions
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id              :bigint           not null, primary key
#  name            :string
#  email           :string
#  company_id      :bigint
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  member_group_id :bigint
#  token           :string
#
class Member < ApplicationRecord
  has_secure_token
  belongs_to :company
  belongs_to :member_group
  
  has_many :member_tests, dependent: :destroy
  has_many :test_groups, through: :member_group
  has_many :tests, through: :test_groups

  validates :name, :email, presence: true
  validates :name, uniqueness: { scope: :company_id }

  def matrix
    matrix = {}
    member_group.test_groups.order(:position).find_each do |test_group|
      matrix[test_group.name] = test_group.tests.order(:module).map do |test|
        member_test = member_tests.find_by(test: test)
        is_active = member_test.present? && !member_test.passed?
        is_passed = !!member_test&.passed? || false
        {
          id: test.id,
          name: test.name,
          all_questions_count: test.questions.count,
          questions_count: test.questions_count,
          pass_count: test.pass_count,
          value: test.value,
          module: test.module,
          description: test.description,
          is_passed: is_passed,
          is_active: is_active
        }
      end
    end

    matrix
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[show edit update destroy close_test]

  def index
    @members = current_company.members
  end

  def show; end

  def new
    @member = current_company.members.new
  end

  def edit; end

  def create
    @member = current_company.members.new(member_params)
    if @member.save
      redirect_to @member, notice: 'Member was successfully created.'
    else
      render :new
    end
  end

  def update
    if @member.update(member_params)
      redirect_to @member, notice: 'Member was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @member.destroy
    redirect_to members_url, notice: 'Member was successfully destroyed.'
  end

  def close_test
    member_test = @member.member_tests.find_by(test_id: params[:test_id])
    if member_test.nil?
      @member.member_tests.create(test_id: params[:test_id], status: :passed)
    else
      member_test.update(status: :passed)
    end
    redirect_to @member, notice: 'Test was successfully closed.'
  end

  private

    def set_member
      @member = current_company.members.find(params[:id])
    end

    def member_params
      params.require(:member).permit(:name, :email, :member_group_id)
    end
end

app/views/members/_form.slim
= semantic_form_for member do |f| 
  = f.inputs do
    = f.input :name
    = f.input :email
    = f.input :member_group, collection: current_company.member_groups.pluck(:name, :id)
  = f.actions
    = f.action :cancel, as: :link, button_html: { class: 'btn btn--secondary' }
    = f.action :submit, as: :button, button_html: { class: 'btn btn--primary' }

app/views/members/edit.slim
= render 'layouts/form' do
  .new-form
    .new-form--content
      .new-form--content--title
        h1 Editing Member
      .new-form--content--form
        = render 'form', member: @member
        .new-form--content--form--image.member-img

app/views/members/index.slim
 = render "layouts/table" do

  h1 Members
  = link_to 'New Member', new_member_path, class: 'btn btn--primary right'

  .table-outer
    table.table.table-striped.table--members
      thead
        tr
          th Name
          th Email
          th Member Group
          th Current test
          th Passed tests
          th Score
          th Actions

      tbody
        - @members.each do |member|
          tr
            td = link_to member.name, member, class: 'link'
            td = member.email
            td 
              - if member.member_group_id?
                = link_to member.member_group.name, member_group_path(member.member_group), class: 'link'
            - current_test = member.member_tests.where.not(status: :passed).last
            td = "#{current_test&.test&.test_group&.name} (#{current_test&.test&.name})"
            td = member.member_tests.where(status: :passed).count
            td = member.member_tests.where(status: :passed).joins(:test).sum('tests.value').to_i
            td
              = link_to 'edit', edit_member_path(member), class: 'btn btn--white btn--inline'
              = link_to 'delete', member, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn--black btn--inline'
              .btn.btn--black.btn--inline.public-page-url-btn data-link="#{user_matrix_url(token: member.token)}" Public page
  <br>

app/views/members/new.slim
= render 'layouts/form' do
  .new-form
    .new-form--content
      .new-form--content--title
        h1 New Member
      .new-form--content--form
        = render 'form', member: @member
        .new-form--content--form--image.member-img

app/views/members/show.slim
= render "layouts/table" do
  .title
    h1
      = @member.name
      .value-subtitle = " (#{@member.member_tests.where(status: :passed).joins(:test).sum('tests.value').to_i})"
    h4 = @member.member_group&.name || '--'
  .show-page-actions
    .btn.btn--primary.public-page-url-btn data-link="#{user_matrix_url(token: @member.token)}" Public page
    = link_to 'New member test', new_member_test_path(member_id: @member.id), class: 'btn btn--black'
    = link_to 'Edit', edit_member_path(@member), class: 'btn btn--black'
    = link_to 'Destroy', @member, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn--black btn--inline'
.table-container
  = render partial: "layouts/matrix", locals: { member: @member, tests_container: @member  }